### ISSUE TITLE
Cannot run due to installation issues

### ISSUE THREAD

**Issue by Filco306** [Felix-Petersen/difflogic#2]
Hello! :) 

First of all, really cool paper!! I wish to use it, but there are some installation issues. 

```bash
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install difflogic
```

I get the output: 

```bash
$ pip install --upgrade difflogic
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: difflogic in /home/filco306/.local/lib/python3.8/site-packages (0.0.0)
Collecting difflogic
  Using cached difflogic-0.1.0.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2fbg7kd4/difflogic_f249148a2c3347d280f1fab1669b0e7c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2fbg7kd4/difflogic_f249148a2c3347d280f1fab1669b0e7c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zybeuryc
         cwd: /tmp/pip-install-2fbg7kd4/difflogic_f249148a2c3347d280f1fab1669b0e7c/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2fbg7kd4/difflogic_f249148a2c3347d280f1fab1669b0e7c/setup.py", line 28, in <module>
        ext_modules=[CUDAExtension('difflogic_cuda', [
      File "/home/filco306/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 983, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/filco306/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1098, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/home/filco306/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2125, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9c/18/e7ee8ec8a895f000411853174636f6a90480076da43ca3df40e1e4875fcc/difflogic-0.1.0.tar.gz#sha256=979ce845a494bdf8ebeeb94d61f3bbf1ae018257ee5b048f936567b53fc115a1 (from https://pypi.org/simple/difflogic/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Requirement already satisfied: numpy in /home/filco306/.local/lib/python3.8/site-packages (from difflogic) (1.22.0)
Requirement already satisfied: torch>=1.9.0 in /home/filco306/.local/lib/python3.8/site-packages (from difflogic) (1.12.1+cu113)
Requirement already satisfied: typing-extensions in /home/filco306/.local/lib/python3.8/site-packages (from torch>=1.9.0->difflogic) (3.10.0.0)
WARNING: Error parsing requirements for jupyter: [Errno 2] No such file or directory: '/home/filco306/.local/lib/python3.8/site-packages/jupyter-1.0.0.dist-info/METADATA'
WARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

Would you know what the issue is? Thank you in advance!

**Comment by Felix-Petersen** [comment]
It looks like CUDA is either not installed or you did not set the `CUDA_HOME` environment variable. (An additional pointer: https://github.com/pytorch/extension-cpp/issues/26)

**Comment by Filco306** [comment]
Hello again, 

Thank you for your reply! Actually, it is quite strange. I managed to install it in one environment, and I can successfully start training the MNIST example. However, I built my own training, and I get the error: 

```bash
GPUassert: an illegal memory access was encountered difflogic/cuda/difflogic_kernel.cu 407
```

from `loss.backward()`.

**Comment by Felix-Petersen** [comment]
Hi, for me, this code lead to two issues:

1. `device = torch.device("cuda:1")`:

Multiple GPUs are not supported, and I think this constellation will have some tensors on "cuda" which is device 0, and others on "cuda:1" which is device 1.
So, the fix would be to just use "cuda" and specify the GPU to be used via `export CUDA_VISIBLE_DEVICES=1`.

2. For me, `Func.cross_entropy` did not work as expected, but that was probably dependent on the PyTorch version, so I just replaced it with `torch.nn.BCELoss()` which worked in my PyTorch version.

**Comment by Filco306** [comment]
Thank you! It is working now; I think the bug was in the gpu choice. 

Again, thank you for this fascinating work! I am very excited to work with this and try it out with several applications!
